name: flutter_firebase_notification
description: Sending notifications to a Flutter application using Firebase Cloud Messaging

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_core: ^1.4.0
  firebase_messaging: ^10.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.5.3

flutter:
  uses-material-design: true
